"""empty message

Revision ID: 76857fad189a
Revises: 97bbe4c4bd30
Create Date: 2021-01-31 13:19:31.476050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76857fad189a'
down_revision = '97bbe4c4bd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###
